### ISSUE TITLE
SHA-256 Hashing Not Working

### ISSUE THREAD

**Issue by johndanahy** [jlolling/talendcomp_tHashRow#19]
Hi Team

I have successfully installed tHashRow as a component in Talent Option Studio. MD-5 and SHA-1 hashing works perfect. However, when I select SHA-256 to hash the same column of data and return a hash without any other config changes than for the other two hash algorithms, the job simply shows the join to the next component (i.e. between tHashRow and my SQL connection as 'Starting'. It never advances further. The other components of the job also oddly show 1 row processed (the other algorithms show the actual number of rows which in the example I am using is 244 rows).  This only happens when I select SHA-256 as the Hash Type.

Are there any differences in config I may need to implement please?

Thanks in advance.

**Comment by rbtrtr** [comment]
Hi...I have tested the sha-256 algorithm, but instead of the behaviour you reported I received an exception. This is fixes in the open [pull request](https://github.com/jlolling/talendcomp_tHashRow/pull/20). 
You can fix it also on your own by replacing line number 26 in file tHashRow_java.xml with this line.
`<ITEM NAME="SHA256" VALUE="SHA-256"/> `

This should fix the problem. If not please let us known.

**Comment by robertrichter** [comment]
Hi...I have tested the sha-256 algorithm, but instead of the behaviour you reported I received an exception. This is fixes in the open [pull request](https://github.com/jlolling/talendcomp_tHashRow/pull/20). 
You can fix it also on your own by replacing line number 26 in file tHashRow_java.xml with this line.
`<ITEM NAME="SHA256" VALUE="SHA-256"/> `

This should fix the problem. If not please let us known.

**Comment by johndanahy** [comment]
Perfect. That worked following a reload of the components in Talent Open Studio and a restart of TOS itself. The component prompted me to reselect the Hash Type when I opened the Job. Once I reselected that it worked like the other hash types. Perfect. 

Many thanks for the prompt attention. Very helpful.

**Comment by johndanahy** [comment]
Perfect. That worked following a reload of the components and a reload of Talent. The component prompted me to reselect the Hash Type. Once I had done that it worked a charm.

Many thanks for the prompt attention. Very helpful.
